-- +goose Up

ALTER TYPE metrics.monitoring_service_type ADD VALUE IF NOT EXISTS 'PROMETHEUS_ETHEREUM_CALLS_SERVICE' AFTER 'ASSET_PRICES';
ALTER TYPE metrics.monitoring_service_type ADD VALUE IF NOT EXISTS 'PROMETHEUS_ETH_NODE_SCANNER' AFTER 'PROMETHEUS_ETHEREUM_CALLS_SERVICE';
ALTER TYPE metrics.monitoring_service_type ADD VALUE IF NOT EXISTS 'PROMETHEUS_NODE_SCANNER' AFTER 'PROMETHEUS_ETH_NODE_SCANNER';
ALTER TYPE metrics.monitoring_service_type ADD VALUE IF NOT EXISTS 'PROMETHEUS_METAMONITORING' AFTER 'PROMETHEUS_NODE_SCANNER';

-- +goose Down

-- Nothing to do because We only added fields